#include <iostream> 
using namespace std;
int main()
{ 
    int x=-1; 
     try 
     { 
         cout << "Inside try n\n"; 
         if (x <0) 
         { 
        throw x; 
        cout << "After throw n\n";
         }
         
     } 
     catch (int x) { 
         cout << "Exception Caught n\n"; 
         
     } 
         cout << "After catch n\n"; 
         return 0;
    
}
